import { readFileSync } from 'node:fs'
import { existsSync } from 'node:fs'
import { join } from 'node:path'

const root = new URL('..', import.meta.url).pathname

function read(path) {
  return readFileSync(join(root, path), 'utf8')
}

function assertContains(path, expected) {
  const content = read(path)
  if (!content.includes(expected)) {
    throw new Error(`${path} is missing expected content: ${expected}`)
  }
}

function assertNotContains(path, unexpected) {
  const content = read(path)
  if (content.includes(unexpected)) {
    throw new Error(`${path} still contains unexpected content: ${unexpected}`)
  }
}

function assertExists(path) {
  if (!existsSync(join(root, path))) {
    throw new Error(`${path} does not exist`)
  }
}

function assertMissing(path) {
  if (existsSync(join(root, path))) {
    throw new Error(`${path} should not exist`)
  }
}

assertExists('docs/zh-Hans/README.md')
assertExists('docs/zh-Hans/deployment.md')
assertExists('docs/zh-Hans/backup-restore.md')
assertExists('docs/zh-Hans/security.md')
assertExists('docs/zh-Hans/production-readiness.md')
assertExists('docs/zh-Hans/database-indexes.md')
assertExists('docs/en/README.md')
assertExists('docs/en/deployment.md')
assertExists('docs/en/backup-restore.md')
assertExists('docs/en/security.md')
assertExists('docs/en/production-readiness.md')
assertExists('docs/en/database-indexes.md')
assertExists('docs/ja/README.md')
assertExists('docs/ja/deployment.md')
assertExists('docs/ja/backup-restore.md')
assertExists('docs/ja/security.md')
assertExists('docs/ja/production-readiness.md')
assertExists('docs/ja/database-indexes.md')
assertExists('.github/SECURITY.md')
assertExists('playwright.config.ts')
assertExists('tests/e2e/public-smoke.spec.ts')
assertExists('scripts/verify-deploy.mjs')
assertExists('scripts/verify-staging.mjs')
assertExists('scripts/audit-production.mjs')
assertExists('scripts/seed-basics.mjs')
assertMissing('README_en.md')
assertMissing('docs/deployment.md')
assertMissing('SECURITY.md')
assertMissing('backend/README.md')
assertMissing('frontend/README.md')

assertContains('backend/.env.example', 'ADMIN_PANEL_ALLOWED_ROLES=')
assertContains('backend/.env.example', 'PANEL_INTERNAL_TOKEN=')
assertContains('backend/.env.example', 'ADMIN_PATH=')
assertContains('backend/.env.example', 'STRAPI_CORS_ORIGINS=')
assertContains('backend/.env.example', 'STRAPI_ADMIN_WAF_CONFIRMED=')
assertContains('backend/.env.example', 'CLOUDINARY_NAME=')
assertContains('frontend/.env.example', 'API_TIMEOUT_MS=')
assertContains('package.json', '"@strapi/admin>axios"')
assertContains('package.json', '"@strapi/cloud-cli>axios"')
assertContains('package.json', '"audit:prod"')
assertContains('package.json', '"verify:staging"')
assertContains('backend/config/admin.ts', 'ADMIN_PATH')
assertContains('backend/config/middlewares.ts', 'STRAPI_CORS_ORIGINS')
assertContains('backend/config/middlewares.ts', 'assertProductionCorsOrigins')
assertContains('backend/src/index.ts', 'STRAPI_ADMIN_WAF_CONFIRMED')
assertContains('scripts/verify-deploy.mjs', 'ADMIN_PATH')
assertContains('scripts/verify-deploy.mjs', 'Formal production deployments require CLOUDINARY')
assertContains('scripts/verify-deploy.mjs', 'HTTPS origins only')
assertContains('scripts/audit-production.mjs', 'GHSA-r5fr-rjxr-66jc')
assertContains('scripts/audit-production.mjs', 'STRAPI_ADMIN_PUBLIC')
assertContains('scripts/verify-staging.mjs', 'STAGING_BACKUP_RESTORE_VERIFIED')
assertContains('scripts/verify-staging.mjs', 'STAGING_CRON_SINGLE_INSTANCE_VERIFIED')
assertContains('docs/zh-Hans/database-indexes.md', 'CREATE INDEX CONCURRENTLY IF NOT EXISTS works_featured_idx')
assertContains('docs/en/production-readiness.md', 'STRAPI_ADMIN_PUBLIC=true')
assertContains('playwright.config.ts', 'workers: 1')
assertContains('playwright.config.ts', 'pnpm --dir frontend start')
assertContains('backend/src/api/panel/services/collection-config.ts', "readOnly: true")
assertContains('backend/src/api/panel/services/rate-limit.ts', 'PANEL_INTERNAL_TOKEN')
assertContains('backend/src/api/panel/services/audit-log.ts', 'recordAdminAuditLog')
assertContains('backend/src/api/panel/services/system-health.ts', 'getSystemHealth')
assertContains('backend/src/api/panel/services/content-quality.ts', 'scanContentQuality')
assertContains('backend/src/api/panel/controllers/panel.ts', 'runBulkAction')
assertContains('backend/src/api/work/content-types/work/schema.json', '"isFeatured"')
assertContains('backend/src/api/work/content-types/work/schema.json', '"featuredPriority"')
assertContains('backend/src/api/online-event/content-types/online-event/schema.json', '"eventFormat"')
assertContains('backend/src/api/online-event/content-types/online-event/schema.json', '"platform"')
assertContains('backend/src/api/online-event/content-types/online-event/schema.json', '"country"')
assertContains('backend/src/api/online-event/content-types/online-event/schema.json', '"sourceName"')
assertContains('backend/src/api/offline-event/content-types/offline-event/schema.json', '"city"')
assertNotContains('backend/src/api/offline-event/content-types/offline-event/schema.json', '"district"')
assertContains('backend/src/api/offline-event/content-types/offline-event/schema.json', '"venue"')
assertContains('backend/src/api/offline-event/content-types/offline-event/schema.json', '"sourceName"')
assertContains('backend/src/api/announcement/content-types/announcement/schema.json', '"isPinned"')
assertExists('backend/src/api/friend-link/content-types/friend-link/schema.json')
assertContains('backend/src/api/friend-link/content-types/friend-link/schema.json', '"friend_links"')
assertContains('backend/src/api/panel/services/collection-config.ts', "'friend-links'")
assertContains('backend/src/api/panel/services/content-quality.ts', 'featured-missing-image')
assertContains('backend/src/api/panel/services/content-quality.ts', 'offline-event-missing-region')
assertContains('backend/src/api/panel/services/content-quality.ts', 'online-event-missing-region')
assertContains('backend/src/api/panel/services/content-quality.ts', 'source-name-missing-url')
assertContains('backend/src/api/panel/services/content-quality.ts', 'duplicate-event-source')
assertContains('backend/src/api/panel/controllers/panel.ts', 'set-featured-priority')
assertContains('frontend/src/lib/api.ts', 'getFeaturedWorks')
assertContains('frontend/src/lib/api.ts', 'getFriendLinks')
assertContains('frontend/src/lib/api.ts', 'getAllEvents')
assertContains('frontend/src/lib/api.ts', 'getEventLocationRecords')
assertContains('frontend/src/lib/api.ts', 'EventKindFilter')
assertContains('frontend/src/components/events-with-filters.tsx', 'onKindChange')
assertContains('frontend/src/components/event-filters.tsx', '<select')
assertContains('frontend/src/components/event-filters.tsx', 'locationRecords')
assertNotContains('frontend/src/components/event-filters.tsx', '<input')
assertNotContains('frontend/src/components/event-filters.tsx', 'district')
assertNotContains('frontend/src/components/event-filters.tsx', 'EventFormatFilter')
assertNotContains('frontend/src/components/event-filters.tsx', 'EventSourcePlatformFilter')
assertNotContains('frontend/src/components/event-filters.tsx', 'sourcePlatform')
assertNotContains('frontend/src/components/events-with-filters.tsx', 'platform:')
assertNotContains('frontend/src/components/events-with-filters.tsx', 'district')
assertContains('frontend/src/lib/utils/event-location.ts', '台湾地区')
assertContains('frontend/src/components/event-card.tsx', 'getEventDisplayPlace')
assertNotContains('frontend/src/components/event-card.tsx', 'getEventFormatLabel')
assertContains('frontend/src/app/[locale]/offline-events/page.tsx', 'const city = normalizeEventLocationName')
assertNotContains('frontend/src/app/[locale]/offline-events/page.tsx', 'district')
assertContains('frontend/src/app/[locale]/online-events/page.tsx', 'const country = normalizeEventLocationName')
assertContains('frontend/src/lib/api.ts', '...RESEARCH_ENTRY_LIST_POPULATE')
assertExists('frontend/src/app/[locale]/events/page.tsx')
assertExists('frontend/src/app/[locale]/research-archives/page.tsx')
assertContains('frontend/src/app/[locale]/research-archives/page.tsx', "href: '#research-themes'")
assertContains('frontend/src/app/[locale]/research-archives/page.tsx', 'getResearchSubjects')
assertExists('frontend/src/app/[locale]/manage/friend-links/page.tsx')
assertContains('frontend/src/app/[locale]/page.tsx', 'researchEntries.length > 0')
assertContains('frontend/src/app/[locale]/research-archives/[slug]/page.tsx', "t['research.title']")
assertContains('frontend/src/app/[locale]/research-archives/[slug]/page.tsx', 'addTableOfContents')
assertExists('frontend/src/app/[locale]/research-archives/themes/page.tsx')
assertContains('frontend/src/lib/admin-panel.ts', 'relation-multiselect')
assertContains('frontend/src/lib/admin-panel.ts', "relationKey: 'research-citations'")
assertNotContains('frontend/src/lib/admin-panel.ts', "name: 'school'")
assertNotContains('frontend/src/lib/admin-panel.ts', "name: 'affiliations'")
assertNotContains('frontend/src/lib/admin-panel.ts', "name: 'spoiler_scope'")
assertNotContains('backend/src/api/panel/services/collection-config.ts', 'spoiler_scope')
assertNotContains('frontend/src/components/research-filter.tsx', 'RESEARCH_AFFILIATIONS')
assertNotContains('frontend/src/app/[locale]/research-archives/page.tsx', 'SpoilerProgressSelect')
assertNotContains('frontend/src/app/[locale]/research-archives/[slug]/page.tsx', 'SpoilerGate')
assertContains('backend/src/api/panel/controllers/panel.ts', 'RESEARCH_CURATOR_UID')
assertContains('backend/src/api/panel/controllers/panel.ts', '.findFirst')
assertContains('frontend/src/components/admin/research-curator-form.tsx', 'strapiAdminUrl')
assertContains('frontend/src/app/[locale]/manage/page.tsx', '/manage/research-curator')
assertContains('frontend/src/components/header.tsx', '/research-archives')
assertContains('frontend/src/components/header.tsx', '/events')
assertContains('frontend/src/components/friend-links-section.tsx', 'FriendLinksSection')
assertContains('frontend/src/app/[locale]/online-events/page.tsx', 'searchParams')
assertContains('frontend/src/app/[locale]/offline-events/page.tsx', 'searchParams')
assertContains('backend/src/api/admin-audit-log/content-types/admin-audit-log/schema.json', '"admin_audit_logs"')
assertContains('backend/src/api/content-quality-issue/content-types/content-quality-issue/schema.json', '"content_quality_issues"')
assertContains('backend/src/api/job-lock/content-types/job-lock/schema.json', '"job_locks"')
assertContains('frontend/src/app/api/image-proxy/route.ts', "urlObj.protocol !== 'https:'")
assertContains('frontend/src/app/api/image-proxy/route.ts', "startsWith('image/')")
assertContains('frontend/src/app/api/image-proxy/route.ts', 'createLimitedImageStream')
assertContains('frontend/src/lib/sanitize.ts', "FORBID_ATTR: ['style']")
assertContains('backend/src/api/sync-log/content-types/sync-log/schema.json', '"retry"')
assertContains('backend/src/api/sync-log/content-types/sync-log/schema.json', '"stage"')
assertContains('frontend/src/app/[locale]/manage/admin-audit-logs/page.tsx', 'Audit Logs')
assertContains('frontend/src/app/[locale]/manage/system-health/page.tsx', 'System Health')
assertContains('frontend/src/app/[locale]/manage/content-quality/page.tsx', 'Content Quality')
assertContains('frontend/src/app/[locale]/manage/bulk-actions/page.tsx', 'Bulk Actions')
assertContains('frontend/src/app/sitemap.ts', 'sitemapEntry')
assertContains('frontend/src/app/sitemap.ts', 'getAllCollectionItems')
assertContains('frontend/src/proxy.ts', 'x-schale-locale')
assertContains('frontend/src/proxy.ts', 'firstSegment !== pathnameLocale')
assertContains('frontend/src/app/layout.tsx', 'getHtmlLang')
assertContains('frontend/src/app/layout.tsx', 'lang={htmlLang}')
assertContains('backend/src/utils/job-lock.ts', 'locked_until')
assertContains('backend/src/utils/job-lock.ts', 'where({ id: lock.id, owner: lock.owner })')
assertContains('backend/src/api/panel/services/rate-limit.ts', 'RATE_LIMIT_TABLE')
assertContains('backend/src/api/panel/services/rate-limit.ts', 'transaction(async')
assertContains('backend/src/api/panel/services/content-quality.ts', 'QUALITY_SCAN_PAGE_SIZE')
assertContains('backend/src/api/panel/services/content-quality.ts', 'replacementDetectedAt')
assertContains('backend/src/api/panel/services/content-quality.ts', 'school_ref: true')
assertNotContains('backend/src/api/panel/services/content-quality.ts', 'limit: 1000')
assertContains('backend/src/api/panel/services/audit-export.ts', 'AUDIT_EXPORT_MAX_ROWS')
assertContains('backend/src/api/panel/services/audit-export.ts', 'X-Export-Truncated')
assertContains('backend/src/api/bilibili-subscription/services/bilibili-subscription.ts', 'processDueRetries')
assertContains('backend/src/api/bilibili-subscription/services/bilibili-subscription.ts', 'scheduleSubscriptionRetry')
assertNotContains('backend/src/api/bilibili-subscription/services/bilibili-subscription.ts', '5 * 60 * 1000); // 5分钟')

console.log('Regression checks passed')
